name: Deploy Back-end
on:
  workflow_dispatch:
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Autenticação no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Construir e enviar a imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: sgcmapi/
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sgcmapi:latest
  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: webacademyufac/deploy-action@main
        with:
          app-id: ${{ secrets.DEPLOY_APP_ID }}
          api-key: ${{ secrets.DEPLOY_API_KEY }}
